######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 25 08:06:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drivebutton.h mainwindow.h jhead.h
FORMS += mainwindow.ui
SOURCES += drivebutton.cpp main.cpp mainwindow.cpp exif.c gpsinfo.c iptc.c jhead.c jpgfile.c makernote.c myglob.c paths.c
