######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 25 08:06:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drivebutton.h mainwindow.h EXIF.H
FORMS += mainwindow.ui
SOURCES += drivebutton.cpp main.cpp mainwindow.cpp EXIF.CPP
